# GPTContext default config — matches config.py _DEFAULT_CONFIG

MAX_TOTAL_TOKENS: 12000
MAX_FILE_TOKENS: 5000
MAX_FILE_SIZE_MB: 1
BASE_DIR: "."
CONTEXT_OUTPUT_FILENAME: ".gptcontext.txt"
MESSAGE_OUTPUT_FILENAME: ".gptcontext_message.txt"
GPTCONTEXT_CACHE_DIRNAME: ".gptcontext-cache"
OPENAI_MODEL: "gpt-3.5-turbo"
ENCODING_NAME: "cl100k_base"

description: Default preset for GPTContext
long_description: |
  This preset is designed to capture a wide range of file types and configurations
  commonly found in software projects. It includes various programming languages, configuration files,
  and documentation formats, while excluding directories that typically contain build artifacts,
  dependencies, or IDE-specific configurations. The preset aims to provide a comprehensive context
  for understanding the project without unnecessary clutter from temporary files or non-essential directories.

exclude:
- .git/
- .svn/
- .hg/
- node_modules/
- __pycache__/
- dist/
- build/
- .venv/
- env/
- .mypy_cache/
- .pytest_cache/
- .vscode/
- .idea/
- .gptcontext-cache/
- .DS_Store/
- __snapshots__/
- .coverage/
- .cache/
- .gptcontext.txt
- .gptcontext_message.txt
- README.md
- CHANGELOG.md
- LICENSE
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- SECURITY.md

include_exts:
- .py
- .md
- .js
- .ts
- .jsx
- .tsx
- .json
- .toml
- .yaml
- .yml
- .html
- .css
- .scss
- .sass
- .less
- .java
- .go
- .rs
- .cpp
- .c
- .h
- .hpp
- .cs
- .swift
- .kt
- .m
- .sh
- .bash
- .zsh
- .ps1
- .pl
- .rb
- .php
- .ini
- .cfg
- .env
- .txt
- .xml


use_default_excludes: true
